language: go
install:
- go get "github.com/stretchr/testify"
- go get ./...
before_script:
- tar xvf config.tar
- go vet ./...
- go test -v -coverprofile=coverage.txt -covermode=atomic
before_install:
- openssl aes-256-cbc -K $encrypted_4e4ce833f09f_key -iv $encrypted_4e4ce833f09f_iv
  -in config.tar.enc -out config.tar -d
after_success:
- bash <(curl -s https://codecov.io/bash)
