language:
- go
install:
- go get "github.com/stretchr/testify"
- go get ./...
before_script:
- tar xvf config.tar
- go vet ./simplecrypto
- go vet .
- go test -v -coverprofile=coverage.txt -covermode=atomic
script:
- VERSION=0.0.1 make build
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: gcs
  access_key_id: GOOGWQV5QPSY7K57O42Q
  secret_access_key:
    secure: ypm1QVDCycP8lnq0DTYjDsR4kKFdxnRlaHPnAMEG28dt6BZR5CoUnqOdrGrhYte6AccAc7MG9f0/FLjFjtwkhkMXgp4MYUT2LxWbXleCeJDwSPd/4KHUV2XuUr9htuSEJn/cZ7hm/cfWB5AKljXl98d3iHhToZRd2ScRQDl/T2DqvWiHzWoGP69mrcYq9PyVdbN1TX88sS4tUkw6xQtpnd6T/hcXODrPyPGcixmOz4qFyUJxTQTQs2pVv+iC1CJ3Vt3zoft+nCRFlLHa3Pb+nhT8SrA79d8PCWcRojpVWGuQxROscARJuc/fISt5NbvUdlLDSRsLT0dF2OIn8FcsIAvlGg7NV6S2zDD0X6ghOt2RfPjY+3E/KgsnKhTVrIaClInjzqI+G/V84Jz0vPGcRAsUHhrzBvpqV4smWb4d/kSzSjJ1BVpurcEexe+VmfC4SnFX2cxa9K27SS1KnwbXjIXRP5BdOMRYK1J7DJ6eNyQG5b8clrn1COsrctxaeSS8A26k3hOghDdPHiSVRV9wjX77GiDRHItEll9OUcqdjlHP1zBORnnUkteRa9AbpYDjSmF9woW7AWUibV6W4MwhQtlbEVwCYeycuA8rDF8vn4mmVH9ZvgdZH66ykRZ5YMPqBabA/qVi5tgpQp2pVRir2ZBx0QRakHbdgUTBDqZ7jyk=
  bucket: gcloud-crypto-binaries
  skip_cleanup: true
  local_dir: build
  upload-dir: build_$TRAVIS_BUILD_NUMBER
  on:
    repo: GregorioDiStefano/gcloud-crypto
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_4e4ce833f09f_key -iv $encrypted_4e4ce833f09f_iv
  -in config.tar.enc -out config.tar -d
